/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

package zanshin.core.texts

import zanshin.core.texts.Activity.*

/**
 * What a reading's "good for" and "avoid" lists name, so that the same act
 * under different wordings ("weddings", "marriage", "taking a bride") can be
 * compared across annotations. The source wording stays in the catalog, one
 * `wording.<key>` entry each; only wordings that name the same act share an
 * entry here.
 */
enum class Activity {
    EVERYTHING,
    CELEBRATION,

    WEDDING,
    BETROTHAL,
    MARRIAGE_TALKS,

    JOURNEY,
    COMING_HOME,
    SEA_TRAVEL,
    MOVING_HOUSE,
    BRANCH_FAMILY,
    RETIRING,

    BUILDING,
    EXTENDING_HOUSE,
    HOUSE_REPAIRS,
    RAISING_PILLARS,
    RIDGEPOLE,
    ROOFING,
    BUILDING_GATES,
    OPENING_GATES,
    STONE_WALLS,
    BUILDING_STOREHOUSES,
    OPENING_STOREHOUSES,
    DRIVING_NAILS,
    CLIMBING_HIGH,

    MOVING_EARTH,
    DIGGING,
    BREAKING_GROUND,
    GROUND_BREAKING_RITES,
    LAYING_FOUNDATIONS,
    FILLING_HOLES,
    WELLS,

    SOWING,
    PLANTING,
    GRAFTING,
    HARVESTING,
    CUTTING_GRASS,
    FELLING_TREES,
    OPENING_RICE_BALES,

    OPENING_SHOP,
    BUYING,
    BUYING_LAND,
    ACQUIRING,
    RECEIVING_MONEY,
    MONEY_TALKS,
    LENDING_MONEY,
    STORING,
    COLLECTING,

    CONTRACTS,
    AGREEMENTS,
    PROMISES,
    NEGOTIATIONS,
    CONSULTATIONS,
    DISPUTES,
    FIXING_DECISIONS,
    QUICK_DECISIONS,

    BEGINNINGS,
    NEW_VENTURES,
    STARTING_SCHOOL,
    STARTING_LESSONS,
    ENTRANCE_EXAMS,
    TAKING_UP_OFFICE,
    ANNOUNCEMENTS,

    TAKING_MEDICINE,
    STARTING_MEDICINE,
    ACUPUNCTURE,
    VISITING_THE_SICK,

    FUNERALS,
    BURIAL,
    MEMORIAL_SERVICES,
    MOURNING,
    BUILDING_GRAVES,

    SHRINE_RITES,
    PRAYER,
    SHRINES_AND_ALTARS,
    DEVOTION,
    MAKING_WISHES,

    SEWING,
    NEW_CLOTHES,
    FIRST_WEARING,
    NAMING,
    HAIRCUTS,

    CLEARING_OUT,
    THROWING_AWAY,
    PUTTING_IN_ORDER,
    MAKING_THINGS,
    UNCLEAN_HOUSE,
    HELPING_OTHERS,

    BLADES,
    BLOODSHED,
    HUNTING,
    FIRE,
    HEAVY_EATING,
    CARELESS_WORDS,
    HASTE,
    CALM,

    // The Tibetan activity lists (SPEC §5.10)
    OFFERINGS,
    SACRED_SUPPORTS,
    DIVINATION,
    LEARNING_ASTROLOGY,
    STUDYING_SCRIPTURE,
    LEARNING_ARTS,
    MEDICAL_TREATMENT,
    SURGERY,
    STUDYING_MEDICINE,
    BUYING_HOME,
    MAKING_A_WILL,
    MAKING_WEAPONS,
    HEALTH_AND_WEALTH,
    PACIFYING,
    INCREASING,
    CONTROLLING,
    DESTROYING,

    // The White Beryl's karaṇas and lunar dates (SPEC §5.11)
    LAWSUITS,
    JUDGING_CASES,
    OATHS,
    STATECRAFT,
    WAR,
    KILLING,
    ROBBERY,
    POISON,
    BUYING_LIVESTOCK,
    TRADING,
    GIVING_OUT,
    DOWRY,
    MOVING_GOODS,
    TAMING_ANIMALS,
    CATTLE_WORK,
    FIELD_WORK,
    TEACHING_DHARMA,
    HEARING_DHARMA,
    DHARMA_PRACTICE,
    VIRTUE,
    ORDINATION,
    PROSTRATIONS,
    MANTRAS,
    AMULETS,
    SERVING_TEACHER,
    BRAHMINS,
    CONSECRATION,
    WASHING_HAIR,
    AVERTING_RITES,
    SUPPRESSING_SRI,
    FIRE_OFFERINGS,
    PROSPERITY_RITES,
    EMPOWERMENT,
    CURSING,
    HEARTH,
    DAMS,
    SERVANTS,
    BATHING,
    BREWING,
    PARENTS,
    GIVING_A_CHILD,
    BLOODLETTING,
    MAKING_MEDICINE,
    LASTING_WORK,
    MOVING_WORK,
    FRIENDSHIP,
    GOOD_FORTUNE,

    // The White Beryl's weekdays
    MEETING_THE_GREAT,
    PETITIONS,
    RECONCILIATION,
    BANNERS,
    HORSE_RACING,
    SPECTACLES,
    FEASTS,
    GAMES,
    SADDLING,
    DAIRY,
    RAISING_DOGS,
    SMOKE_OFFERINGS,
    RECITATION,
    VOWS,
    STUDY,
    PERFUME,
    ORNAMENTS,
    WATER_WORK,
    LOVE,

    // The kun phan me long's other activity boxes (SPEC §5.10)
    HORSES,
    RAINMAKING,

    // The White Beryl's mansion verses (SPEC §5.10)
    BON_RITES,
    PITCHING_TENTS,
    TAKING_ELIXIRS;

    val english: String get() = gloss(this)
}

/**
 * The families the activities are drawn by, one glyph each (SPEC §10.4): the
 * day's summary line shows which families its annotations name good and to
 * avoid. Declared in the order that line shows them.
 */
enum class ActivityFamily {
    EVERYTHING,
    CELEBRATION,
    WEDDING,
    JOURNEY,
    SEA,
    MOVING_HOUSE,
    BUILDING,
    EARTH,
    WELL,
    FIELD,
    LIVESTOCK,
    TRADE,
    AGREEMENT,
    DISPUTE,
    AUTHORITY,
    BEGINNING,
    LEARNING,
    MEDICINE,
    FUNERAL,
    SHRINE,
    PRAYER,
    VOWS,
    OFFERING,
    SACRED,
    RITE,
    PACIFYING,
    INCREASING,
    CONTROLLING,
    DESTROYING,
    CLOTHES,
    HAIRCUT,
    BATHING,
    NAME,
    HOUSEHOLD,
    KIN,
    BLADE,
    FIRE,
    CONDUCT;

    val english: String get() = gloss(this)
}

/** The family an activity is drawn with. Every activity has one: the `when` is exhaustive. */
val Activity.family: ActivityFamily
    get() = when (this) {
        EVERYTHING -> ActivityFamily.EVERYTHING
        CELEBRATION -> ActivityFamily.CELEBRATION
        WEDDING, BETROTHAL, MARRIAGE_TALKS, DOWRY -> ActivityFamily.WEDDING
        JOURNEY, COMING_HOME -> ActivityFamily.JOURNEY
        SEA_TRAVEL -> ActivityFamily.SEA
        MOVING_HOUSE, BRANCH_FAMILY, RETIRING, BUYING_HOME -> ActivityFamily.MOVING_HOUSE
        BUILDING, EXTENDING_HOUSE, HOUSE_REPAIRS, RAISING_PILLARS, RIDGEPOLE, ROOFING, BUILDING_GATES, OPENING_GATES,
        STONE_WALLS, BUILDING_STOREHOUSES, OPENING_STOREHOUSES, DRIVING_NAILS, CLIMBING_HIGH, MAKING_THINGS, PITCHING_TENTS -> ActivityFamily.BUILDING
        MOVING_EARTH, DIGGING, BREAKING_GROUND, GROUND_BREAKING_RITES, LAYING_FOUNDATIONS, FILLING_HOLES -> ActivityFamily.EARTH
        WELLS -> ActivityFamily.WELL
        SOWING, PLANTING, GRAFTING, HARVESTING, CUTTING_GRASS, FELLING_TREES, OPENING_RICE_BALES -> ActivityFamily.FIELD
        OPENING_SHOP, BUYING, BUYING_LAND, ACQUIRING, RECEIVING_MONEY, MONEY_TALKS, LENDING_MONEY, STORING, COLLECTING -> ActivityFamily.TRADE
        CONTRACTS, AGREEMENTS, PROMISES, NEGOTIATIONS, CONSULTATIONS, FIXING_DECISIONS, QUICK_DECISIONS, MAKING_A_WILL -> ActivityFamily.AGREEMENT
        BEGINNINGS, NEW_VENTURES, ANNOUNCEMENTS -> ActivityFamily.BEGINNING
        STARTING_SCHOOL, STARTING_LESSONS, ENTRANCE_EXAMS, STUDYING_SCRIPTURE, LEARNING_ARTS, LEARNING_ASTROLOGY,
        DIVINATION, STUDYING_MEDICINE -> ActivityFamily.LEARNING
        TAKING_MEDICINE, STARTING_MEDICINE, ACUPUNCTURE, VISITING_THE_SICK, MEDICAL_TREATMENT, SURGERY, TAKING_ELIXIRS -> ActivityFamily.MEDICINE
        FUNERALS, BURIAL, MEMORIAL_SERVICES, MOURNING, BUILDING_GRAVES -> ActivityFamily.FUNERAL
        SHRINE_RITES, SHRINES_AND_ALTARS -> ActivityFamily.SHRINE
        PRAYER, DEVOTION, MAKING_WISHES -> ActivityFamily.PRAYER
        OFFERINGS, SMOKE_OFFERINGS -> ActivityFamily.OFFERING
        SACRED_SUPPORTS -> ActivityFamily.SACRED
        HEALTH_AND_WEALTH -> ActivityFamily.RITE
        // The four actions apart: a day names one good where it avoids another (SPEC §10.7).
        PACIFYING -> ActivityFamily.PACIFYING
        INCREASING -> ActivityFamily.INCREASING
        CONTROLLING -> ActivityFamily.CONTROLLING
        DESTROYING, CURSING, SUPPRESSING_SRI -> ActivityFamily.DESTROYING
        SEWING, NEW_CLOTHES, FIRST_WEARING -> ActivityFamily.CLOTHES
        HAIRCUTS -> ActivityFamily.HAIRCUT
        NAMING -> ActivityFamily.NAME
        CLEARING_OUT, THROWING_AWAY, PUTTING_IN_ORDER, UNCLEAN_HOUSE -> ActivityFamily.HOUSEHOLD
        BLADES, BLOODSHED, HUNTING, MAKING_WEAPONS -> ActivityFamily.BLADE
        FIRE -> ActivityFamily.FIRE
        CALM, HASTE, CARELESS_WORDS, HEAVY_EATING, HELPING_OTHERS -> ActivityFamily.CONDUCT
        DISPUTES, LAWSUITS, JUDGING_CASES -> ActivityFamily.DISPUTE
        OATHS -> ActivityFamily.AGREEMENT
        TAKING_UP_OFFICE, STATECRAFT, MEETING_THE_GREAT, PETITIONS -> ActivityFamily.AUTHORITY
        WAR, KILLING, ROBBERY, POISON -> ActivityFamily.BLADE
        TRADING, GIVING_OUT, MOVING_GOODS -> ActivityFamily.TRADE
        FIELD_WORK -> ActivityFamily.FIELD
        BUYING_LIVESTOCK, TAMING_ANIMALS, CATTLE_WORK, SADDLING, DAIRY, RAISING_DOGS, HORSES -> ActivityFamily.LIVESTOCK
        TEACHING_DHARMA, HEARING_DHARMA -> ActivityFamily.LEARNING
        DHARMA_PRACTICE, VIRTUE, PROSTRATIONS, MANTRAS, AMULETS, RECITATION -> ActivityFamily.PRAYER
        ORDINATION, VOWS, SERVING_TEACHER, BRAHMINS -> ActivityFamily.VOWS
        CONSECRATION -> ActivityFamily.SACRED
        BATHING, WASHING_HAIR, PERFUME -> ActivityFamily.BATHING
        AVERTING_RITES, FIRE_OFFERINGS, PROSPERITY_RITES, EMPOWERMENT, RAINMAKING, BON_RITES -> ActivityFamily.RITE
        HEARTH -> ActivityFamily.BUILDING
        DAMS -> ActivityFamily.EARTH
        BREWING -> ActivityFamily.HOUSEHOLD
        PARENTS, GIVING_A_CHILD, SERVANTS, FRIENDSHIP -> ActivityFamily.KIN
        BLOODLETTING, MAKING_MEDICINE -> ActivityFamily.MEDICINE
        LASTING_WORK, MOVING_WORK -> ActivityFamily.CONDUCT
        GOOD_FORTUNE -> ActivityFamily.CELEBRATION
        RECONCILIATION -> ActivityFamily.AGREEMENT
        BANNERS -> ActivityFamily.SACRED
        HORSE_RACING, SPECTACLES, FEASTS, GAMES -> ActivityFamily.CELEBRATION
        STUDY -> ActivityFamily.LEARNING
        ORNAMENTS -> ActivityFamily.CLOTHES
        WATER_WORK -> ActivityFamily.WELL
        LOVE -> ActivityFamily.WEDDING
    }

/** The times of day the rokuyō name good or bad. They are hours, not acts. */
enum class DayTime { MORNING, NOON, AFTERNOON, EVENING }

object Activities {
    private fun of(vararg activities: Activity): Set<Activity> = activities.toSet()

    /** Every wording of the "good for" and "avoid" lists, by its catalog key, with the act it names. */
    val BY_WORDING: Map<String, Set<Activity>> = mapOf(
        "everything" to of(EVERYTHING),
        "celebrations" to of(CELEBRATION),

        "weddings" to of(WEDDING),
        "marriage" to of(WEDDING),
        "taking_a_bride" to of(WEDDING),
        "bringing_in_a_bride" to of(WEDDING),
        "betrothal_gifts" to of(BETROTHAL),
        "marriage_talks" to of(MARRIAGE_TALKS),

        "travel" to of(JOURNEY),
        "setting_out" to of(JOURNEY),
        "setting_out_on_journeys" to of(JOURNEY),
        "long_journeys" to of(JOURNEY),
        "journeys_in_any_direction" to of(JOURNEY),
        "coming_home" to of(COMING_HOME),
        "boarding_ships" to of(SEA_TRAVEL),
        "sea_travel" to of(SEA_TRAVEL),
        "sea_voyages" to of(SEA_TRAVEL),
        "moving_house" to of(MOVING_HOUSE),
        "setting_up_a_branch_family" to of(BRANCH_FAMILY),
        "retiring" to of(RETIRING),

        "building" to of(BUILDING),
        "building_a_house" to of(BUILDING),
        "any_building_work" to of(BUILDING),
        "extending_a_house" to of(EXTENDING_HOUSE),
        "house_repairs" to of(HOUSE_REPAIRS),
        "raising_pillars" to of(RAISING_PILLARS),
        "raising_the_ridgepole" to of(RIDGEPOLE),
        "roofing" to of(ROOFING),
        "building_gates" to of(BUILDING_GATES),
        "opening_gates" to of(OPENING_GATES),
        "building_stone_walls" to of(STONE_WALLS),
        "building_storehouses" to of(BUILDING_STOREHOUSES),
        "opening_a_shop_gate_or_storehouse" to of(OPENING_SHOP, OPENING_GATES, OPENING_STOREHOUSES),
        "driving_nails" to of(DRIVING_NAILS),
        "climbing_high" to of(CLIMBING_HIGH),

        "moving_earth" to of(MOVING_EARTH),
        "earthworks" to of(MOVING_EARTH),
        "turning_soil" to of(MOVING_EARTH),
        "digging" to of(DIGGING),
        "breaking_ground" to of(BREAKING_GROUND),
        "ground_breaking_rites" to of(GROUND_BREAKING_RITES),
        "laying_foundations" to of(LAYING_FOUNDATIONS),
        "filling_holes" to of(FILLING_HOLES),
        "digging_wells" to of(WELLS),
        "wells" to of(WELLS),

        "sowing" to of(SOWING),
        "planting" to of(PLANTING),
        "grafting" to of(GRAFTING),
        "harvesting" to of(HARVESTING),
        "cutting_grass" to of(CUTTING_GRASS),
        "felling_trees" to of(FELLING_TREES),
        "opening_rice_bales" to of(OPENING_RICE_BALES),

        "opening_a_shop" to of(OPENING_SHOP),
        "opening_a_business" to of(OPENING_SHOP),
        "buying" to of(BUYING),
        "buying_land" to of(BUYING_LAND),
        "acquiring_things" to of(ACQUIRING),
        "receiving_money" to of(RECEIVING_MONEY),
        "money_talks" to of(MONEY_TALKS),
        "lending_or_borrowing_money" to of(LENDING_MONEY),
        "storing" to of(STORING),
        "collecting" to of(COLLECTING),

        "contracts" to of(CONTRACTS),
        "agreements" to of(AGREEMENTS),
        "promises" to of(PROMISES),
        "negotiations" to of(NEGOTIATIONS),
        "consultations" to of(CONSULTATIONS),
        "disputes" to of(DISPUTES),
        "fixing_decisions" to of(FIXING_DECISIONS),
        "quick_decisions" to of(QUICK_DECISIONS),

        "beginnings" to of(BEGINNINGS),
        "new_beginnings" to of(BEGINNINGS),
        "new_ventures" to of(NEW_VENTURES),
        "starting_school" to of(STARTING_SCHOOL),
        "starting_lessons" to of(STARTING_LESSONS),
        "entrance_exams" to of(ENTRANCE_EXAMS),
        "taking_up_office" to of(TAKING_UP_OFFICE),
        "announcements" to of(ANNOUNCEMENTS),

        "taking_medicine" to of(TAKING_MEDICINE),
        "starting_medicine" to of(STARTING_MEDICINE),
        "acupuncture" to of(ACUPUNCTURE),
        "visiting_the_sick" to of(VISITING_THE_SICK),

        "funerals" to of(FUNERALS),
        "funerals_custom" to of(FUNERALS),
        "burial" to of(BURIAL),
        "interments" to of(BURIAL),
        "memorial_services" to of(MEMORIAL_SERVICES),
        "mourning" to of(MOURNING),
        "building_graves" to of(BUILDING_GRAVES),

        "shrine_rites" to of(SHRINE_RITES),
        "prayer" to of(PRAYER),
        "prayers_to_gods_and_buddhas" to of(PRAYER),
        "shrines_and_altars" to of(SHRINES_AND_ALTARS),
        "devotion" to of(DEVOTION),
        "making_wishes" to of(MAKING_WISHES),

        "sewing" to of(SEWING),
        "new_clothes" to of(NEW_CLOTHES),
        "first_wearing_of_new_clothes" to of(FIRST_WEARING),
        "naming" to of(NAMING),
        "naming_a_child" to of(NAMING),
        "haircuts" to of(HAIRCUTS),

        "clearing_out" to of(CLEARING_OUT),
        "throwing_things_away" to of(THROWING_AWAY),
        "putting_things_in_order" to of(PUTTING_IN_ORDER),
        "making_things" to of(MAKING_THINGS),
        "an_unclean_house" to of(UNCLEAN_HOUSE),
        "helping_others" to of(HELPING_OTHERS),

        "blades" to of(BLADES),
        "bloodshed" to of(BLOODSHED),
        "hunting" to of(HUNTING),
        "fire" to of(FIRE),
        "eating_and_drinking_heavily" to of(HEAVY_EATING),
        "careless_words" to of(CARELESS_WORDS),
        "haste" to of(HASTE),
        "calm" to of(CALM),

        "offerings_to_deities" to of(OFFERINGS),
        "taking_a_new_home" to of(MOVING_HOUSE),
        "setting_up_supports" to of(SACRED_SUPPORTS),
        // Henning's word for rab gnas: his mansions for it are those whose White Beryl verse names consecration good (T2.5).
        "installing_a_deity" to of(CONSECRATION),
        "astrology_and_divination" to of(DIVINATION),
        "learning_astrology" to of(LEARNING_ASTROLOGY),
        "studying_scripture" to of(STUDYING_SCRIPTURE),
        "learning_music_or_dance" to of(LEARNING_ARTS),
        "planting_and_sowing" to of(PLANTING, SOWING),
        "laying_the_foundation_of_a_home" to of(LAYING_FOUNDATIONS),
        "medical_treatment" to of(MEDICAL_TREATMENT),
        "surgical_treatment" to of(SURGERY),
        "studying_medicine" to of(STUDYING_MEDICINE),
        "buying_a_home" to of(BUYING_HOME),
        "making_a_will" to of(MAKING_A_WILL),
        "making_weapons" to of(MAKING_WEAPONS),
        "health_and_wealth" to of(HEALTH_AND_WEALTH),
        "pacifying_activity" to of(PACIFYING),
        "increasing_activity" to of(INCREASING),
        "controlling_activity" to of(CONTROLLING),
        "destructive_activity" to of(DESTROYING),

        "lawsuits" to of(LAWSUITS),
        "pacifying_rites" to of(PACIFYING),
        "increasing_rites" to of(INCREASING),
        "power_rites" to of(CONTROLLING),
        "fierce_rites" to of(DESTROYING),
        "buying_livestock" to of(BUYING_LIVESTOCK),
        "teaching_dharma" to of(TEACHING_DHARMA),
        "hearing_dharma" to of(HEARING_DHARMA),
        "dharma_practice" to of(DHARMA_PRACTICE),
        "washing_the_hair" to of(WASHING_HAIR),
        "funeral_rites" to of(FUNERALS),
        "giving_anything_out" to of(GIVING_OUT),
        "worship_of_deities" to of(OFFERINGS),
        "averting_rites" to of(AVERTING_RITES),
        "suppressing_sri" to of(SUPPRESSING_SRI),
        "gtad_and_sri_rites" to of(SUPPRESSING_SRI),
        "ordination" to of(ORDINATION),
        "consecration" to of(CONSECRATION),
        "enthronement" to of(TAKING_UP_OFFICE),
        "building_a_hearth" to of(HEARTH),
        "digging_ponds_and_wells" to of(DIGGING, WELLS),
        "digging_ponds_canals_and_wells" to of(DIGGING, WELLS),
        "digging_ponds_and_canals" to of(DIGGING),
        "building_dams" to of(DAMS),
        "building_flood_dikes" to of(DAMS),
        "fire_offerings" to of(FIRE_OFFERINGS),
        "retinue_and_marriage" to of(SERVANTS, WEDDING),
        "trade" to of(TRADING),
        "taking_servants" to of(SERVANTS),
        "prostrations" to of(PROSTRATIONS),
        "bloodletting_and_moxibustion" to of(BLOODLETTING),
        "bloodletting" to of(BLOODLETTING),
        "leading_an_army" to of(WAR),
        // Qualified by a direction: they count for neither side (SPEC §5.10); the date's reading keeps them.
        "war_not_east" to of(),
        "war_not_south" to of(),
        "war_not_south_or_west" to of(),
        "war_south_or_west" to of(),
        "attacking_enemies" to of(WAR),
        "subduing_enemies" to of(WAR),
        "judging_disputes" to of(JUDGING_CASES),
        "quarrels" to of(DISPUTES),
        "oaths" to of(OATHS),
        "making_images" to of(SACRED_SUPPORTS),
        "building_temples_and_stupas" to of(SACRED_SUPPORTS),
        "building_temples" to of(SACRED_SUPPORTS),
        "bathing" to of(BATHING),
        "tying_on_amulets" to of(AMULETS),
        "breaking_in_livestock" to of(TAMING_ANIMALS),
        "prosperity_rites" to of(PROSPERITY_RITES),
        "empowerment" to of(EMPOWERMENT),
        "gaining_wealth" to of(HEALTH_AND_WEALTH),
        "giving_a_child_away" to of(GIVING_A_CHILD),
        "paying_debts" to of(LENDING_MONEY),
        "buying_goods" to of(BUYING),
        "buying_servants_and_goods" to of(SERVANTS, BUYING),
        "buying_fields" to of(BUYING_LAND),
        "robbery" to of(ROBBERY),
        "hanging_doors" to of(BUILDING_GATES),
        "virtuous_work" to of(VIRTUE),
        "learning_writing_astrology_and_crafts" to of(STUDY, LEARNING_ASTROLOGY, MAKING_THINGS),
        "work_with_rock" to of(BUILDING),
        "council" to of(CONSULTATIONS),
        "brewing_beer" to of(BREWING),
        "field_work" to of(FIELD_WORK),
        "virtue" to of(VIRTUE),
        "lasting_work" to of(LASTING_WORK),
        "work_on_the_move" to of(MOVING_WORK),
        "preparing_medicine" to of(MAKING_MEDICINE),
        "reciting_mantras" to of(MANTRAS),
        "mantras" to of(MANTRAS),
        "serving_the_teacher" to of(SERVING_TEACHER),
        "the_brahmins_affairs" to of(BRAHMINS),
        "the_parents_affairs" to of(PARENTS),
        "honouring_and_service" to of(SERVING_TEACHER),
        "work_with_cattle" to of(CATTLE_WORK),
        "gathering_merit" to of(VIRTUE),
        "unsteady_and_moving_work" to of(MOVING_WORK),
        "moving_goods" to of(MOVING_GOODS),
        "gathering_power" to of(CONTROLLING),
        "prayers_for_good_fortune" to of(PRAYER),
        "making_friends" to of(FRIENDSHIP),
        "joyful_occasions" to of(CELEBRATION),
        "buying_and_trading" to of(BUYING, TRADING),
        "killing_others" to of(KILLING),
        "preparing_poison" to of(POISON),
        "harsh_work" to of(DESTROYING),
        "cursing" to of(CURSING),
        "worship_of_brahmins" to of(BRAHMINS),
        "affairs_of_state" to of(STATECRAFT),
        "weapon_tormas" to of(DESTROYING),
        "killing_and_robbing" to of(KILLING, ROBBERY),
        "works_of_good_fortune" to of(GOOD_FORTUNE),
        "killing_people" to of(KILLING),
        "robbing" to of(ROBBERY),
        "wished_for_increase" to of(INCREASING),

        "founding_a_palace" to of(BUILDING),
        "meeting_great_people" to of(MEETING_THE_GREAT),
        "planting_trees" to of(PLANTING),
        "planting_flowers" to of(PLANTING),
        "raising_banners" to of(BANNERS),
        "averting_thieves" to of(AVERTING_RITES),
        "horse_racing" to of(HORSE_RACING),
        "breaking_in_horses_and_livestock" to of(TAMING_ANIMALS),
        "breaking_in_oxen" to of(TAMING_ANIMALS),
        "breaking_in_horses" to of(TAMING_ANIMALS),
        "spectacles" to of(SPECTACLES),
        "magic_shows" to of(SPECTACLES),
        "saddling" to of(SADDLING),
        "crafts_in_gold_wood_leather_and_bone" to of(MAKING_THINGS),
        "work_with_fire" to of(FIRE),
        "smoke_offerings" to of(SMOKE_OFFERINGS),
        "reciting_scripture" to of(RECITATION),
        "presenting_petitions" to of(PETITIONS),
        "study" to of(STUDY),
        "going_into_the_forest" to of(JOURNEY),
        "feasts" to of(FEASTS),
        "games" to of(GAMES),
        "making_perfumes" to of(PERFUME),
        "auspicious_work" to of(GOOD_FORTUNE),
        "carrying_out_the_dead" to of(FUNERALS),
        "harsh_words" to of(CARELESS_WORDS),
        "temple_foundations" to of(SACRED_SUPPORTS, LAYING_FOUNDATIONS),
        "cutting_hair_and_nails" to of(HAIRCUTS),
        "sewing_tents" to of(SEWING),
        "building_towns" to of(BUILDING),
        "sending_out_wealth" to of(GIVING_OUT),
        "sending_out_livestock" to of(GIVING_OUT),
        "reconciliation" to of(RECONCILIATION),
        "lawsuits_and_disputes" to of(LAWSUITS, DISPUTES),
        "work_with_water" to of(WATER_WORK),
        "offerings_to_nagas" to of(OFFERINGS),
        "taking_elixirs" to of(TAKING_ELIXIRS),
        "putting_on_ornaments" to of(ORNAMENTS),
        "matchmaking" to of(MARRIAGE_TALKS),
        "dairy_work" to of(DAIRY),
        "grain_work" to of(FIELD_WORK),
        "offerings_to_the_lama" to of(OFFERINGS),
        "receiving_wealth" to of(RECEIVING_MONEY),
        "war" to of(WAR),
        "martial_skills" to of(WAR),
        "appointing_generals" to of(TAKING_UP_OFFICE),
        "fighting_enemies" to of(WAR),
        "hurling_zor" to of(DESTROYING),
        "hurling_mdos_torma_and_zor" to of(DESTROYING),
        "directing_magic" to of(DESTROYING),
        "black_rites" to of(DESTROYING),
        "collecting_debts" to of(LENDING_MONEY),
        "taking_new_lands" to of(WAR),
        "destroying_forts" to of(WAR),
        "raising_dogs" to of(RAISING_DOGS),
        "moxibustion" to of(BLOODLETTING),
        "work_with_gold_coral_and_swords" to of(MAKING_THINGS, MAKING_WEAPONS),
        "divination" to of(DIVINATION),
        "astrology" to of(DIVINATION),
        "crafts" to of(MAKING_THINGS),
        "woodwork" to of(MAKING_THINGS),
        "ironwork" to of(MAKING_THINGS),
        "work_with_jewels" to of(MAKING_THINGS),
        "metal_and_jewel_work" to of(MAKING_THINGS),
        "gatherings" to of(CELEBRATION),
        "markets" to of(TRADING),
        "seeking_land" to of(BUYING_LAND),
        "taking_out_a_corpse" to of(FUNERALS),
        "taking_in_a_dog" to of(RAISING_DOGS),
        "setting_up_a_gate" to of(BUILDING_GATES),
        "poetry_and_grammar" to of(STUDY),
        "writing_treatises" to of(STUDY),
        "learning_the_sciences" to of(STUDY),
        "learning_writing_and_astrology" to of(STUDY, LEARNING_ASTROLOGY),
        "studying_the_dharma" to of(STUDYING_SCRIPTURE),
        "teaching_and_hearing_the_dharma" to of(TEACHING_DHARMA, HEARING_DHARMA),
        "mandala_rites" to of(DHARMA_PRACTICE),
        "taking_vows" to of(VOWS),
        "restoring_vows" to of(VOWS),
        "seeking_connections" to of(FRIENDSHIP),
        "seeking_friends" to of(FRIENDSHIP),
        "taking_a_retinue" to of(SERVANTS),
        "presenting_offerings" to of(OFFERINGS),
        "farming" to of(FIELD_WORK),
        "building_new_houses" to of(BUILDING),
        "consorting_with_women" to of(LOVE),
        "feuds" to of(DISPUTES),
        "long_life_and_prosperity_rites" to of(PROSPERITY_RITES),
        "acquiring_goods_and_livestock" to of(ACQUIRING, BUYING_LIVESTOCK),
        "trading_land_and_houses" to of(BUYING_LAND),
        "serving_the_king" to of(STATECRAFT),

        // The kun phan me long's other activity boxes
        "building_walls" to of(BUILDING),
        "setting_up_hearth_and_pillars" to of(HEARTH, RAISING_PILLARS),
        "preparing_food_and_brewing" to of(BREWING),
        "giving_and_taking_loans" to of(LENDING_MONEY),
        "planting_trees_and_flowers" to of(PLANTING),
        "virtuous_acts_for_the_living" to of(VIRTUE),
        "manuring_and_breaking_in_oxen" to of(FIELD_WORK, TAMING_ANIMALS),
        "giving_gifts_and_dowries" to of(DOWRY),
        "feeding_up_horses" to of(HORSES),
        "treating_horses_mules_and_donkeys" to of(HORSES),
        "calling_prosperity_and_bon_rites" to of(PROSPERITY_RITES),
        "bathing_and_washing_the_hair" to of(BATHING, WASHING_HAIR),
        "composing_treatises_and_learning_poetics" to of(STUDY),
        "bringing_rain" to of(RAINMAKING),
        "thread_cross_and_torma_rites" to of(AVERTING_RITES),
        "honouring_and_petitioning" to of(PETITIONS),
        "ordination_teaching_and_empowerment" to of(ORDINATION, TEACHING_DHARMA, HEARING_DHARMA, EMPOWERMENT, STUDY, DHARMA_PRACTICE),

        // The White Beryl's mansion verses (SPEC §5.10)
        "giving_vows" to of(VOWS),
        "moving_a_grave" to of(BUILDING_GRAVES),
        "bon_rites" to of(BON_RITES),
        "making_offerings" to of(OFFERINGS),
        "paying_back" to of(LENDING_MONEY),
        "driving_out_thieves" to of(WAR),
        "ending_mourning" to of(MOURNING),
        "rites_against_enemies" to of(DESTROYING),
        "stopping_rumours" to of(DISPUTES),
        "four_activities_but_special_cases" to of(PACIFYING, INCREASING, CONTROLLING, DESTROYING),
        "ritual_services" to of(DHARMA_PRACTICE),
        "great_gatherings" to of(CELEBRATION),
        "works_for_the_living" to of(HEALTH_AND_WEALTH),
        "marriage_alliances" to of(WEDDING),
        "summoning_life" to of(HEALTH_AND_WEALTH),
        "dowries" to of(DOWRY),
        "sending_away_a_son_or_sister" to of(GIVING_A_CHILD),
        "drawing_the_effigy" to of(DESTROYING),
        "suppressing_enemies" to of(DESTROYING),
        "expelling_demons" to of(DESTROYING),
        "acquiring_goats" to of(BUYING_LIVESTOCK),
        "planting_gardens" to of(PLANTING),
        "selling_land" to of(BUYING_LAND),
        "funerals_of_the_low_born" to of(),
        "power_and_fierce_rites" to of(CONTROLLING, DESTROYING),
        "supporting_widows_and_widowers" to of(HELPING_OTHERS),
        "setting_up_or_removing_a_gtad" to of(SUPPRESSING_SRI),
        "cremation" to of(FUNERALS),
        "honouring_a_spiritual_friend" to of(SERVING_TEACHER),
        "paying_in_goats" to of(GIVING_OUT),
        "pacifying_and_increasing_rites" to of(PACIFYING, INCREASING),
        "white_work" to of(VIRTUE),
        "giving_or_taking_a_bride" to of(WEDDING),
        "restoring_temples_and_stupas" to of(SACRED_SUPPORTS),
        "investiture" to of(TAKING_UP_OFFICE),
        "taking_things_in" to of(ACQUIRING),
        "pitching_tents" to of(PITCHING_TENTS),
        "meeting_relatives" to of(FRIENDSHIP),
        "seizing_prisoners" to of(JUDGING_CASES),
        "paying_out" to of(GIVING_OUT),
        "opening_storehouses" to of(OPENING_STOREHOUSES),
        "planting_fields" to of(SOWING),
        "opening_a_cellar" to of(OPENING_STOREHOUSES),
        "war_and_raids" to of(WAR, ROBBERY),
        "gifts" to of(GIVING_OUT),
        "funeral_feasts" to of(FUNERALS),
        "taking_land_a_fort_or_a_dwelling" to of(BUYING_LAND),
        "teaching" to of(TEACHING_DHARMA),
        "protecting_life_and_prosperity" to of(HEALTH_AND_WEALTH),
        "taking_in_wealth_and_livestock" to of(ACQUIRING, BUYING_LIVESTOCK),
        "building_forts" to of(BUILDING),
        "claiming_debts" to of(LENDING_MONEY),
        "building_a_pleasure_garden" to of(PLANTING),
        "lawsuits_in_the_east" to of(),
        "sewing_and_pitching_tents" to of(SEWING, PITCHING_TENTS),
        "paying_out_livestock_and_goods" to of(GIVING_OUT),
        "burying_bones" to of(BURIAL),
        "sharing_out_prosperity" to of(GIVING_OUT),
        "a_new_house" to of(MOVING_HOUSE),
        "setting_up_a_door" to of(BUILDING_GATES),
        "dharma_for_the_living" to of(DHARMA_PRACTICE),
        "giving_ornaments" to of(ORNAMENTS),
        "carpentry" to of(MAKING_THINGS),
        "counsel" to of(CONSULTATIONS),
        "temples" to of(SACRED_SUPPORTS),
        "fierce_and_harsh_work" to of(DESTROYING),
        "raising_victory_banners" to of(BANNERS),
        "taking_wealth" to of(RECEIVING_MONEY),
        "subduing_demons" to of(DESTROYING),
        "horses_donkeys_and_mules" to of(HORSES, SADDLING),
        "gaining_what_one_wishes" to of(MAKING_WISHES),
        "fierce_and_increasing_rites" to of(DESTROYING, INCREASING),
        "virtuous_acts" to of(VIRTUE),
        "sending_away_people_or_wealth" to of(GIVING_OUT),
        "gentle_work" to of(PACIFYING),
        "sending_away_a_bride" to of(WEDDING),
        "crafts_and_writing" to of(MAKING_THINGS, STUDY),
        "measuring_out_and_taking_in" to of(TRADING),
        "killing_and_cutting" to of(KILLING),
        "fights_and_disputes" to of(DISPUTES),
        "sri_rites_against_enemies" to of(SUPPRESSING_SRI),
        "repairing_ponds_and_canals" to of(DIGGING),
        "petitioning_the_great" to of(PETITIONS),
        "planting_flowers_and_trees" to of(PLANTING),
        "measuring_livestock" to of(GIVING_OUT),
        "sewing_tents_and_felt" to of(SEWING),
        "pacifying_increasing_power_and_auspicious_rites" to of(PACIFYING, INCREASING, CONTROLLING, GOOD_FORTUNE),
        "summoning_prosperity" to of(PROSPERITY_RITES),
        "practice_and_offering" to of(DHARMA_PRACTICE),
        "drawing_mandalas" to of(DHARMA_PRACTICE),
        "calling_back" to of(AVERTING_RITES),
        "fights" to of(DISPUTES),
        "taking_a_house" to of(MOVING_HOUSE),
        "beginning_small_tasks" to of(BEGINNINGS),
        "taking_sheep_in" to of(BUYING_LIVESTOCK),
        "saddling_and_treating_horses_and_donkeys" to of(SADDLING, HORSES),
        "petitioning" to of(PETITIONS),
        "power_increasing_and_pacifying_rites" to of(CONTROLLING, INCREASING, PACIFYING),
        "paying_out_sheep" to of(GIVING_OUT),
        "giving_wealth" to of(GIVING_OUT),
        "taking_land" to of(BUYING_LAND),
        "pulling_down_temples" to of(),
        "sinful_acts" to of(KILLING),
        "taking_a_new_land" to of(BUYING_LAND),
        "giving_offerings" to of(SERVING_TEACHER),
        "taking_attendants" to of(SERVANTS),
        "taking_over_a_treasury" to of(STORING),
        "quick_accomplishment" to of(MOVING_WORK),
        "presenting_wealth_to_the_great" to of(PETITIONS),
        "works_for_the_living_and_the_dead" to of(HEALTH_AND_WEALTH, FUNERALS),
        "hunting_and_theft" to of(HUNTING, ROBBERY),
        "sending_away_prosperity" to of(GIVING_OUT),
        "destroying_towns" to of(WAR),
        "deceit_and_cheating" to of(ROBBERY),
        "ponds_canals_and_dams" to of(DIGGING, DAMS),
        "settling_deliberations" to of(FIXING_DECISIONS),
        "turning_a_river" to of(WATER_WORK),
        "taming_livestock" to of(TAMING_ANIMALS),
        "pressing_claims" to of(LENDING_MONEY),
        "raising_tents" to of(PITCHING_TENTS),
        "pacifying_increasing_and_power_rites" to of(PACIFYING, INCREASING, CONTROLLING),
        "auspicious_and_virtuous_acts" to of(GOOD_FORTUNE, VIRTUE),
        "sending_goats_away" to of(GIVING_OUT),
        "setting_up_a_loom" to of(MAKING_THINGS),
        "rites_for_life_and_wealth" to of(HEALTH_AND_WEALTH),
        "virtuous_dharma" to of(DHARMA_PRACTICE),
        "carrying_out_a_corpse" to of(FUNERALS),
        "giving_and_taking_a_bride" to of(WEDDING),
        "virtuous_practice" to of(DHARMA_PRACTICE),
        "learning_to_write" to of(STUDY),
        "averting_magic" to of(AVERTING_RITES),
        "the_zor" to of(DESTROYING),
        "attacking" to of(WAR),
        "buying_horses_and_livestock" to of(BUYING_LIVESTOCK),
        "beginning_white_work" to of(VIRTUE, BEGINNINGS),
        "keeping_dogs" to of(RAISING_DOGS),
        "dams_ponds_and_wells" to of(DAMS, DIGGING, WELLS),
        "breaking_and_treating_horses_and_donkeys" to of(SADDLING, TAMING_ANIMALS, HORSES),
        "sending_away_wealth_and_goods" to of(GIVING_OUT),
        "a_bride_neither_given_nor_taken" to of(WEDDING),
        "mdos_for_life_and_prosperity" to of(HEALTH_AND_WEALTH),
        "trading_estates" to of(BUYING_LAND),
        "taking_livestock_and_wealth" to of(RECEIVING_MONEY, BUYING_LIVESTOCK),
        "forts" to of(BUILDING),
        "paying_in_sheep" to of(GIVING_OUT),
        "travelling_south_west" to of(),
        "buying_horses" to of(HORSES),
        "raids" to of(ROBBERY),
        "medicine" to of(MEDICAL_TREATMENT),
        "weapons" to of(MAKING_WEAPONS),
        "donkeys" to of(HORSES),
        "giving_away_goods" to of(GIVING_OUT),
        "ponds" to of(DIGGING),
        "a_new_land" to of(BUYING_LAND),
        "taking_a_dwelling" to of(MOVING_HOUSE),
        "rites_for_long_life" to of(HEALTH_AND_WEALTH),
        "harsh_work_killing_and_cutting" to of(DESTROYING, KILLING),
        "virtuous_and_auspicious_acts" to of(VIRTUE, GOOD_FORTUNE),
        "considered_and_lasting_work" to of(LASTING_WORK),
        "sending_away_goods" to of(GIVING_OUT),
        "councils" to of(CONSULTATIONS),
        "war_and_reconciliation" to of(WAR, RECONCILIATION),
        "breaking_horses_and_livestock_for_oneself" to of(TAMING_ANIMALS),
        "setting_out_south_or_north" to of(),
        "sending_away_cattle" to of(GIVING_OUT),
        "offerings" to of(OFFERINGS),
        "rites_for_relatives" to of(FRIENDSHIP),
        "receiving_guests" to of(FRIENDSHIP),
        "breaking_wild_livestock" to of(TAMING_ANIMALS),
        "shwa_rags" to of(DAMS),
        "setting_up_cattle_and_sheep" to of(CATTLE_WORK),
        "saddling_horses_and_donkeys" to of(SADDLING),
        "trimming_manes" to of(HORSES),
        "suppressing" to of(DESTROYING),
        "most_four_activities" to of(CONTROLLING, DESTROYING, PACIFYING, INCREASING),
        "thieves" to of(ROBBERY),
        "taking_livestock_in" to of(BUYING_LIVESTOCK),
        "a_bride" to of(WEDDING),
        "listening_to_the_dharma" to of(HEARING_DHARMA),
        "quick_works" to of(MOVING_WORK),
        "life_and_prosperity_rites" to of(HEALTH_AND_WEALTH, PROSPERITY_RITES),
        "painting" to of(MAKING_THINGS),
        "taking_a_new_house" to of(MOVING_HOUSE),
        "throwing_mdos_and_torma" to of(DESTROYING),
        "taking_in_goats_and_cattle" to of(BUYING_LIVESTOCK),
        "power_and_increasing_rites" to of(CONTROLLING, INCREASING),
        "long_life_rites_for_a_spiritual_friend" to of(SERVING_TEACHER),
        "paying_out_goats_and_livestock" to of(GIVING_OUT),
        "pitching_tents_not_on_ones_own_estate" to of(),
        "opening_a_grave" to of(BUILDING_GRAVES),
        "theft_and_raids" to of(ROBBERY),
        "opening_ponds_canals_and_storehouses" to of(DIGGING, OPENING_STOREHOUSES),
        "petitioning_and_honouring" to of(PETITIONS, SERVING_TEACHER),
        "most_pacifying_and_fierce_rites" to of(PACIFYING, DESTROYING),
        "dams" to of(DAMS),
        "deity_practice" to of(DHARMA_PRACTICE),
        "restoring_and_making_images" to of(SACRED_SUPPORTS),
        "scattering_grain" to of(SOWING),
        "taking_over_a_storehouse" to of(STORING),
        "crossing_water" to of(JOURNEY),
        "breaking_horses_and_oxen" to of(TAMING_ANIMALS),
        "the_brides_bath" to of(WEDDING, BATHING),
        "ponds_and_canals" to of(DIGGING),
        "saddling_and_treating_horses_donkeys_and_mules" to of(SADDLING, HORSES),
        "laying_out_gardens" to of(PLANTING),
        "taking_in_land_and_forts" to of(BUYING_LAND),
        "most_works_increasing_power_pacifying" to of(INCREASING, CONTROLLING, PACIFYING),
        "giving_away_land_fields_or_forts" to of(GIVING_OUT),
        "opening_grain_stores" to of(OPENING_STOREHOUSES),
        "practice" to of(DHARMA_PRACTICE),
        "selling_fields" to of(BUYING_LAND),
        "guests_going" to of(JOURNEY),
        "measuring_grain" to of(GIVING_OUT),
        "lending" to of(LENDING_MONEY),
        "taking_in_a_bride" to of(WEDDING),
        "restoring_stupas" to of(SACRED_SUPPORTS),
        "gtad_and_fierce_rites" to of(DESTROYING),
        "power_and_increasing_rites_in_general" to of(CONTROLLING, INCREASING),
        "travelling_far" to of(JOURNEY),
        "prosperity_rites_for_wool" to of(PROSPERITY_RITES),
        "taking_in_gains" to of(RECEIVING_MONEY),
        "lawsuits_in_the_south_and_west" to of(),
        "breaking_horses_donkeys_and_mules" to of(TAMING_ANIMALS),
        "ploughing" to of(FIELD_WORK),
        "a_bride_parts_from_her_husband" to of(WEDDING),
        "harsh_speech" to of(CARELESS_WORDS),
        "bad_work" to of(DESTROYING),
        "arraying_for_battle" to of(WAR),
        "suppressing_and_gtad" to of(SUPPRESSING_SRI),
        "destroying_and_robbing" to of(WAR, ROBBERY),
        "burying_the_phur_pa" to of(DESTROYING),
        "battle_and_killing" to of(WAR, KILLING),
        "bad_fights" to of(DISPUTES),
        "summoning_life_and_prosperity" to of(HEALTH_AND_WEALTH, PROSPERITY_RITES),
        "auspicious_acts" to of(GOOD_FORTUNE),
        "building_bridges" to of(WATER_WORK),
        "drawing_water_channels" to of(WATER_WORK),
        "sending_horses_to_the_herd" to of(CATTLE_WORK),
        "sorcery" to of(DESTROYING),
        "giving_away_goats" to of(GIVING_OUT),
        "death_rites" to of(FUNERALS),
        "weapons_and_killing" to of(MAKING_WEAPONS, KILLING),
        "bad_means" to of(DESTROYING),
        "restoring" to of(SACRED_SUPPORTS),
        "sending_messages" to of(ANNOUNCEMENTS),
        "taking_in_goods" to of(ACQUIRING),
        "small_tasks" to of(BEGINNINGS),
        "power_and_fierce_works_for_the_living" to of(CONTROLLING, DESTROYING, HEALTH_AND_WEALTH),
        "mdos_and_torma" to of(AVERTING_RITES),
        "servants_work" to of(SERVANTS),
        "giving_meat_and_butter" to of(GIVING_OUT),
        "travelling_abroad" to of(JOURNEY),
        "royal_affairs" to of(STATECRAFT),
        "pacifying_and_increasing_rites_in_general" to of(PACIFYING, INCREASING),
        "making_gardens" to of(PLANTING),
        "taking_attendants_and_women" to of(SERVANTS, LOVE),
        "buying_horses_livestock_fields_and_houses" to of(BUYING_LIVESTOCK, BUYING_LAND, BUYING_HOME),
        "ploughing_and_planting" to of(FIELD_WORK, PLANTING),
        "appointing_stewards" to of(TAKING_UP_OFFICE),
        "sending_away_grain_and_wealth" to of(GIVING_OUT),
        "ornaments" to of(ORNAMENTS),
        "teaching_and_listening" to of(TEACHING_DHARMA, HEARING_DHARMA),
        "retreat_practice" to of(DHARMA_PRACTICE),
        "taking_in_grain_and_wealth" to of(RECEIVING_MONEY, STORING),
        "a_new_land_or_dwelling" to of(BUYING_LAND, MOVING_HOUSE),
        "prosperity_and_long_life_rites" to of(PROSPERITY_RITES, HEALTH_AND_WEALTH),
        "treating_horses_donkeys_and_mules" to of(HORSES),
        "power_pacifying_and_increasing_rites_in_general" to of(CONTROLLING, PACIFYING, INCREASING),
        "everything_for_the_living" to of(HEALTH_AND_WEALTH),
        // The great black day's «ཤི་གསོན་བྱ་ལས», works for the dead and for the living (WB vol. 2, p. 226).
        "works_for_the_dead_and_the_living" to of(FUNERALS, HEALTH_AND_WEALTH),
        "slaughtering_livestock" to of(KILLING),
        "giving_butter_away" to of(GIVING_OUT),
        "making_tombs_and_hiding_places" to of(BUILDING_GRAVES),
        "sending_a_female_dzo_away" to of(GIVING_OUT),
        "ponds_canals_and_water_works" to of(DIGGING, WATER_WORK),
        "sowing_grain" to of(SOWING),
        "seeking_wealth_for_food" to of(ACQUIRING),
        "paying_out_wealth" to of(GIVING_OUT),
        "summoning_human_prosperity" to of(PROSPERITY_RITES),
        "horses_donkeys_and_gelding" to of(HORSES),
        "taking_a_bride_auspicious" to of(WEDDING),
        "inviting_a_teacher" to of(SERVING_TEACHER),
        "treating_horses" to of(HORSES),
        "sending_away_wealth_goods_horses_and_livestock" to of(GIVING_OUT),
        "saddling_and_racing" to of(SADDLING, HORSE_RACING),
        "being_anothers_teacher" to of(TEACHING_DHARMA),
        "building_a_treasury" to of(BUILDING_STOREHOUSES),
        "treating_and_breaking_horses" to of(HORSES, TAMING_ANIMALS),
        "lasting_works_for_the_living" to of(LASTING_WORK),
        "pacifying_increasing_power_but_special_cases" to of(PACIFYING, INCREASING, CONTROLLING),
        "giving_away_horses_donkeys_and_wealth" to of(GIVING_OUT),
        "opening_vessels" to of(OPENING_STOREHOUSES),
        "buying_female_livestock" to of(BUYING_LIVESTOCK),
        "learning_crafts" to of(LEARNING_ARTS),
        "setting_up_a_sel" to of(AVERTING_RITES),
        "shwa_rags_against_rivers" to of(DAMS),
        "far_travel" to of(JOURNEY),
        "beginning_farming" to of(FIELD_WORK),
        "breeding_livestock" to of(CATTLE_WORK),
        "empowerment_and_taking_vows" to of(EMPOWERMENT, VOWS),
        "gathering_grain_and_wealth" to of(COLLECTING),
        "war_theft_and_raids" to of(WAR, ROBBERY),
        "laying_poison" to of(POISON),
        "wearing_new_clothes" to of(NEW_CLOTHES),
        "distributing_livestock" to of(GIVING_OUT),
        "laying_out_a_corpse" to of(FUNERALS),
        "ones_own_affairs" to of(),
        "gelding_horses_and_donkeys" to of(HORSES),
        "power_and_pacifying_rites" to of(CONTROLLING, PACIFYING),
        "cutting_clothes" to of(SEWING),
        "fierce_work_robbing_and_destroying" to of(DESTROYING, ROBBERY, WAR),
        "giving_a_daughter_away" to of(GIVING_A_CHILD),
        "expelling" to of(WAR),
        "lawsuits_at_home" to of(),
        // A person's own weekdays and birth mansion, WB pp. 330 and 338
        "contests_of_skill" to of(GAMES),
        "pleading_a_case" to of(LAWSUITS),
        "trials_of_strength" to of(GAMES),
        "dice" to of(GAMES),
        "archery" to of(GAMES),
        "stirring_up_strife" to of(DISPUTES),
        "anything" to of(EVERYTHING),
        "every_work" to of(EVERYTHING),
        "serving_the_lama" to of(SERVING_TEACHER),
        "generosity" to of(GIVING_OUT),
        "virtuous_works" to of(VIRTUE),
        "putting_on_ornaments_and_clothes" to of(ORNAMENTS, NEW_CLOTHES),
        "the_works_of_a_house" to of(BUILDING, HOUSE_REPAIRS),
    )

    /** The rokuyō's hours, by wording key. */
    val TIMES: Map<String, Set<DayTime>> = mapOf(
        "the_morning" to setOf(DayTime.MORNING),
        "noon" to setOf(DayTime.NOON),
        "around_noon" to setOf(DayTime.NOON),
        "the_afternoon" to setOf(DayTime.AFTERNOON),
        "morning_and_evening" to setOf(DayTime.MORNING, DayTime.EVENING),
    )

    /** The activities a list of wording keys names; times of day are left out. */
    fun of(wordingKeys: List<String>): Set<Activity> = wordingKeys.flatMap { BY_WORDING[it].orEmpty() }.toSet()
}
