#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""Build app/src/main/assets/cities.tsv, the offline city list (SPEC §10.5).

Source: GeoNames, CC BY 4.0 — https://www.geonames.org/
  https://download.geonames.org/export/dump/cities15000.zip  (cities over 15,000 people)
  https://download.geonames.org/export/dump/countryInfo.txt

Usage: tools/gen_cities.py cities15000.txt countryInfo.txt > app/src/main/assets/cities.tsv

Output columns: name, ASCII name, country, latitude, longitude, IANA zone.
Sorted by population, largest first, so a prefix search returns the most
likely city first without storing the population.
"""

import sys


def main():
    cities_path, countries_path = sys.argv[1], sys.argv[2]
    countries = {}
    with open(countries_path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#"):
                continue
            fields = line.rstrip("\n").split("\t")
            countries[fields[0]] = fields[4]

    rows = []
    with open(cities_path, encoding="utf-8") as f:
        for line in f:
            fields = line.rstrip("\n").split("\t")
            name, ascii_name = fields[1], fields[2]
            lat, lon = float(fields[4]), float(fields[5])
            country = countries.get(fields[8], fields[8])
            population = int(fields[14] or 0)
            zone = fields[17]
            if not zone:
                continue
            rows.append((population, name, ascii_name, country, lat, lon, zone))

    rows.sort(key=lambda r: -r[0])
    out = sys.stdout
    out.write("# GeoNames cities15000, CC BY 4.0, https://www.geonames.org/ — generated by tools/gen_cities.py\n")
    for _, name, ascii_name, country, lat, lon, zone in rows:
        out.write(f"{name}\t{ascii_name}\t{country}\t{lat:.4f}\t{lon:.4f}\t{zone}\n")


if __name__ == "__main__":
    main()
