#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""Generate core/.../astro/Vsop87Earth.kt from the VSOP87D Earth series.

Source file: VSOP87D.ear, Bretagnon & Francou 1988, from the CDS archive
  https://cdsarc.cds.unistra.fr/ftp/VI/81/VSOP87D.ear
(heliocentric ecliptic spherical coordinates, equinox of date).

Usage: tools/gen_vsop87.py path/to/VSOP87D.ear > core/src/main/kotlin/zanshin/core/astro/Vsop87Earth.kt

Only longitude (L) and radius (R) are kept — the sun's latitude is below
1 arcsecond and does not matter for longitudes or rise times — and only
terms with amplitude ≥ THRESHOLD radians (or AU).
"""

import re
import sys

THRESHOLD = 1e-8


def parse(path):
    series = {}
    current = None
    with open(path) as f:
        for line in f:
            if "VSOP87" in line:
                m = re.search(r"VARIABLE (\d).*\*T\*\*(\d)", line)
                current = (int(m.group(1)), int(m.group(2)))
                series[current] = []
            else:
                a, b, c = map(float, line.split()[-3:])
                series[current].append((a, b, c))
    return series


def main():
    series = parse(sys.argv[1])
    out = [
        "/* This Source Code Form is subject to the terms of the Mozilla Public",
        " * License, v. 2.0. If a copy of the MPL was not distributed with this",
        " * file, You can obtain one at https://mozilla.org/MPL/2.0/. */",
        "",
        "// Generated by tools/gen_vsop87.py from VSOP87D.ear (CDS VI/81). Do not edit.",
        f"// Terms with amplitude >= {THRESHOLD:g}.",
        "",
        "package zanshin.core.astro",
        "",
        "internal object Vsop87Earth {",
    ]
    for variable, name in ((1, "L"), (3, "R")):
        powers = sorted(p for (v, p) in series if v == variable)
        names = []
        for p in powers:
            terms = [t for t in series[(variable, p)] if abs(t[0]) >= THRESHOLD]
            if not terms:
                continue
            ident = f"{name}{p}"
            names.append((p, ident))
            out.append(f"    /** {name}{p}: {len(terms)} terms as A, B, C triples. */")
            out.append(f"    private val {ident} = doubleArrayOf(")
            for a, b, c in terms:
                out.append(f"        {a!r}, {b!r}, {c!r},")
            out.append("    )")
            out.append("")
        out.append(f"    /** Series for {name}, index = power of T. */")
        slots = ["null"] * (max(p for p, _ in names) + 1)
        for p, ident in names:
            slots[p] = ident
        out.append(f"    val {name}: Array<DoubleArray?> = arrayOf({', '.join(slots)})")
        out.append("")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
